# Set test path for quad to run through
# waypoint format is [x, y, z, heading]
# path is array of waypoints

path:
  [
  [0, 0, -2, 0],
  [0, 0, -5, 0],
  [0, 0, -2, 0],
  [2, 2, -2, 45],
  [-2, 2, -2, 180],
  [2, -2, -3, -45],
  [0, 0, -2, 0]
  ]
