# zcm-url: "udpm://239.255.76.67:7667?ttl=1"
zcm-url: "ipc"
sim-state: true

color:
  lidar: [128, 0, 0]
  imu-x: [170, 110, 40]
  imu-y: [128, 128, 0]
  imu-z: [0, 128, 128]
  imu-yaw: [0, 0, 128]
  imu-pitch: [0, 0, 0]
  imu-roll: [230, 25, 75]
  pf-pitch: [245, 130, 48]
  pf-roll: [255, 255, 25]
  pf-z: [210, 245, 60]
  pf-z-dot: [60, 180, 75]
  state-pos-x: [255, 0, 0]
  state-pos-y: [0, 255, 0]
  state-pos-z: [0, 0, 255]
  state-vel-x: [240, 50, 230]
  state-vel-y: [128, 128, 128]
  state-vel-z: [250, 190, 190]
  imu-mag-x: [240, 50, 230]
  imu-mag-y: [128, 128, 128]
  imu-mag-z: [250, 190, 190]
  global-update-x: [0, 0, 0]
  global-update-y: [0, 255, 255]
  global-update-z: [255, 0, 255]
  pid-pos-x: [0,0,0]
  pid-pos-y: [0,0,0]
  pid-pos-z: [0,0,0]
  pid-vel-x: [0,0,0]
  pid-vel-y: [0,0,0]
  pid-vel-z: [0,0,0]
  com-thrust: [0,0,0]
  com-roll: [0,0,0]
  com-pitch: [0,0,0]


# Larger line widths will decrease
# performance, slow down draw loop if 
# there is lag in the plotting (specifically
# lag will occur in imu since it is the highest frequency)
line-width: 2
refresh-rate: 60 #Hz
